name       : pulseeffects
version    : 3.0.8
release    : 1
source     :
    - https://github.com/wwmm/pulseeffects/archive/v3.0.8.tar.gz : 4582b4bc4c3ec3d22fc8c54cab53b9c8788df1da404f5c301f4b025d64ce745a
license    : GPL-3.0
component  : multimedia.audio
summary    : PulseAudio equalizer
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - python3-gobject-devel
rundeps    :
    - pulseaudio
    - python3-cairo
    - python3-gobject
    - scipy
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
