name       : pulseeffects
version    : 4.4.7
release    : 13
source     :
    - https://github.com/wwmm/pulseeffects/archive/v4.4.7.tar.gz : 3355e34e3a2d704a2a332f8f0f5432cc51b48b77c39a6c0e35b57797627776d2
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libebur128)
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(sndfile)
    - itstool
    - libboost-devel
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
