name       : pulseeffects
version    : 4.8.4
release    : 25
source     :
    - https://github.com/wwmm/pulseeffects/archive/4.8.4.tar.gz : 12ba3205025d815a747b58636861594f7d1e43a578a5b0411f7794f4c12e5d86
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libebur128)
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - itstool
    - libboost-devel
    - zita-convolver-devel
rundeps    :
    - calf
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - lsp-plugins
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
