name       : pulseeffects
version    : 4.8.3
release    : 23
source     :
    - https://github.com/wwmm/pulseeffects/archive/v4.8.3.tar.gz : c1c1c82ec68baa0d4e44a49b494af1f9e3093f2e62590b3561bff5566048ba56
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libebur128)
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - itstool
    - libboost-devel
    - zita-convolver-devel
rundeps    :
    - calf
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - lsp-plugins
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
