name       : pulseeffects
version    : 3.0.9
release    : 2
source     :
    - https://github.com/wwmm/pulseeffects/archive/v3.0.9.tar.gz : 1733dab5fcbc79ec7c6be0d035bca1767f5b6336b079d9d8bb8fb8273e6936eb
license    : GPL-3.0
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - python3-gobject-devel
rundeps    :
    - gst-python
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - python3-cairo
    - python3-gobject
    - scipy
    - swh-plugins
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
