name       : pulseeffects
version    : 4.8.5
release    : 29
source     :
    - https://github.com/wwmm/easyeffects/archive/refs/tags/v4.8.5.tar.gz : ff04fc3c768c2da9c1a06546b42f6fa7da5b2501b356fd733895b9e12fda7557
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libebur128)
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - itstool
    - libboost-devel
    - zita-convolver-devel
rundeps    :
    - calf
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - lsp-plugins
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
