name       : pulseeffects
version    : 4.4.5
release    : 12
source     :
    - https://github.com/wwmm/pulseeffects/archive/v4.4.5.tar.gz : a91db21055300ed0660820bd0db4f08ebff943e27b80bd0e53ecd1cee6dc6b0e
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libebur128)
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(sndfile)
    - itstool
    - libboost-devel
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
