name       : pulseeffects
version    : 3.1.5
release    : 4
source     :
    - https://github.com/wwmm/pulseeffects/archive/v3.1.5.tar.gz : be57c66015fdbf97fe2efabcce7c3456c31174602bd5369afdc6a1d422976db7
license    : GPL-3.0
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - python3-gobject-devel
rundeps    :
    - gst-python
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - python3-cairo
    - python3-gobject
    - scipy
    - swh-plugins
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
