name       : pulseeffects
version    : 4.4.4
release    : 11
source     :
    - https://github.com/wwmm/pulseeffects/archive/v4.4.4.tar.gz : 5c2de463ae2da81edcf4f01a1730e69b2453333291478d00a8fe45bdbbe4a966
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libebur128)
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(sndfile)
    - itstool
    - libboost-devel
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
