name       : pulseeffects
version    : 4.8.0
release    : 21
source     :
    - https://github.com/wwmm/pulseeffects/archive/v4.8.0.tar.gz : 574695566383a8451bcc48e5c24c201de45369aeff5093e514507cac8f15abc0
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libebur128)
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(sndfile)
    - itstool
    - libboost-devel
rundeps    :
    - calf
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - lsp-plugins
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
