name       : pulseeffects
version    : 4.5.9
release    : 15
source     :
    - https://github.com/wwmm/pulseeffects/archive/v4.5.9.tar.gz : e9624fcf00ba055ea79d6be70b211f69fbb74e384e9a2511b4e512d44214eba3
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : PulseAudio equalizer
description: |
    Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libebur128)
    - pkgconfig(libpulse)
    - pkgconfig(lilv-0)
    - pkgconfig(sndfile)
    - itstool
    - libboost-devel
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - lsp-plugins
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
